---
- name: mkdir opt/xbuild/var
  become: true
  file:
    state: directory
    path: /opt/xbuild/var
    mode: 0777
    owner: root
    group: root

- name: mkdir opt/xbuild/bin
  become: true
  file:
    state: directory
    path: /opt/xbuild/bin
    mode: 0777
    owner: root
    group: root